services:
  - type: web
    name: bot-telegram-moodle
    env: node
    plan: free
    region: oregon
    buildCommand: npm install && npx puppeteer browsers install chrome
    startCommand: node bot-telegram.js
