services:
  - type: web
    name: moodle-telegram-bot
    env: node
    plan: free
    buildCommand: |
      npm install
      npm install -g puppeteer
      npx puppeteer browsers install chrome
    startCommand: node bot-telegram.js
    envVars:
      - key: PUPPETEER_SKIP_CHROMIUM_DOWNLOAD
        value: false
      - key: PUPPETEER_EXECUTABLE_PATH
        value: /opt/render/.cache/puppeteer/chrome/linux-131.0.6778.204/chrome-linux64/chrome
    autoDeploy: true
